In [1]:
# Machine Learning 1 - Python Exercise 

In [2]:
a=[2,1,3]

In [3]:
a

[2, 1, 3]

In [4]:
import numpy as np

In [6]:
np.transpose(a)

array([2, 1, 3])

In [7]:
np.sqrt(sum(np.square(a)))

3.7416573867739413

In [11]:
np.linalg.norm(a)  # you can also use "ord=" to give you the order of the norm

3.7416573867739413

In [12]:
len(a)

3

In [15]:
b=[-3,0,2]

In [14]:
a+b      # strange huh?

[2, 1, 3, -3, 0, 2]

In [16]:
a= np.array([2,1,3])
b=np.array([-3,0,2])

In [18]:
a+b

array([-1,  1,  5])

In [20]:
np.dot(a,b)

0

In [22]:
A = np.matrix('2 1 4; 1 5 2')
A

matrix([[2, 1, 4],
        [1, 5, 2]])

In [23]:
A*2

matrix([[ 4,  2,  8],
        [ 2, 10,  4]])

In [24]:
B = np.matrix('3 2; -1 4; 1 2')
B

matrix([[ 3,  2],
        [-1,  4],
        [ 1,  2]])

In [25]:
A*B

matrix([[ 9, 16],
        [ 0, 26]])

In [26]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
C= np.matrix('4 1; 1 2')
np.linalg.det(C)

6.9999999999999991

In [30]:
A = np.matrix('5 3; 4 2')
B = np.matrix('19; 14')

In [31]:
np.linalg.inv(A)*B

matrix([[ 2.],
        [ 3.]])

In [32]:
A = np.matrix('2 1; 1 2')
np.linalg.eig(A)

(array([ 3.,  1.]), matrix([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]]))

In [33]:
np.linalg.eigvals(A)

array([ 3.,  1.])